config/routes.rb
VotaPrato::Application.routes.draw do
  devise_for :users

  resources :comentarios
  resources :restaurantes

  resources :qualificacaos
  resources :clientes
  root :to => "restaurantes#index" 

  match ':controller(/:action(/:id))(.:format)'
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :comentavel, polymorphic: true
  attr_accessible :comentavel_id, :comentavel_type, :conteudo, :text
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_filter :authenticate_user!
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }

    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])
    respond_to do |format|
      @comentario.save

      format.html {redirect_to @comentario, notice: 'Comentario postado'}
      format.xml {render :xml => @comentario, :status => :created, :location => @comentario }
      format.js
=begin

    respond_to do |format|
     if @comentario.save
format.xml { render :xml => @comentario, :status => :created,
:location => @comentario }
format.js
else
        format.html { redirect_to @comentario, notice: 'Comentario Postado' }
        format.html { render action: "new" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
=end
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
        
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy
    respond_to do |format|
      format.html {redirect_to @comentario, notice: 'Comentario deletado'}
      format.xml {head :ok }
      format.js {head :ok }

    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<p id="comentario_<%= comentario.id %>">
	<%= comentario.conteudo %> -
	<%= link_to '(remover)', comentario, :method => :delete,
	:remote => true,
:id => "remove_comentario_#{comentario.id}" %>
</p>
<%= content_for :js do %>
$('#remove_comentario_<%= comentario.id%>').bind('ajax:success',
function(xhr, result){
$('#comentario_<%=comentario.id%>').remove();
}
);
<% end %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :comentavel_id %><br />
    <%= f.number_field :comentavel_id %>
  </div>
  <div class="field">
    <%= f.label :comentavel_type %><br />
    <%= f.text_field :comentavel_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<div id='novo_comentario'>
	<a href="#" onclick="$('#novo_comentario').children().toggle();">
		Novo comentario
	</a>
	<div id="form_comentario" style="display: none;">
		<%= form_for Comentario.new, :remote => true do |f| %>
		<%= hidden_field :comentario, :comentavel_id,
		:value => comentavel.id %>
		<%= hidden_field :comentario, :comentavel_type, :value => comentavel.class %>
		<div class="field">
			<%= f.label 'conteudo' %><br />
			<%= f.text_area 'conteudo' %>
		</div>
		<div class="actions">
			<%= f.submit %>
			<a href="#"
onclick="$('#novo_comentario').children().toggle();">
Cancelar
</a>
</div>
<% end %>
</div>
</div>
 <%content_for :js do%>
$('#form_comentario').bind('ajax:complete', function(xhr, result){
$('#comentarios').html(result.responseText);
$('#form_comentario textarea').val("")
$('#form_comentario').hide();
$('#novo_comentario > a').show();
});
<%end%>

app/views/comentarios/create.js.erb
<%= render(:partial => "comentarios/comentario",
:collection => @comentario.comentavel.comentarios) %>

app/views/comentarios/edit.html.erb
<html>
<head>
<title>Comentários</title>
	<meta content="charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
	<div id="page">
		<div id="headercom">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li class="active"><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">

						<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>

app/views/comentarios/index.html.erb
<html>
<head>
<title>Comentários</title>
  <meta content="charset=utf-8">
  <link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
  <div id="page">
    <div id="headercom">
      <div class="background">
        <h1><a href="#">Vota Prato</a></h1>
        <ul>
          <li><a href="http://localhost:3000/Clientes">Clientes</a></li>
          <li class="active"><a href="http://localhost:3000/Comentarios">Comentários</a></li>
          <li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
          <li><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
        </ul>
      </div>
    </div>
    <div id="giz">
      <div id="quadroesquerda">
        <div class="block">
          <div class="block-top"></div>
          <div class="block-content">

            <h1>comentarios</h1>

<table>
  <tr>
    <th>Conteudo</th>
    <th>Texto</th>
    <th>Comentavel</th>
    <th>Tipo Comentavel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.conteudo %></td>
    <td><%= comentario.conteudo %></td>
    <td><%= comentario.comentavel_id %></td>
    <td><%= comentario.comentavel_type %></td>
    <td><%= link_to 'Mostrar', comentario %></td>
    <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Deletar', comentario, method: :delete, data: { confirm: 'Tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Comentario', new_comentario_path %>

</div>
          <div class="block-bottom"></div>
        </div>
      </div>
      <div id="quadrodireita">
        <div class="block">
          <div class="block-top"></div>
          <div class="block-content">
            Trabalho Realizado por Rodrigo e Vinicius.
            <br>
            <br>
            Ruby Three Cotia.
          </div>
          <div class="block-bottom"></div>
        </div>

  
      </div>
    </div>
</body>
</html>

app/views/comentarios/new.html.erb
<html>
<head>
<title>Comentários</title>
	<meta content="charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
	<div id="page">
		<div id="headercom">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li class="active"><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">

						<h1>Novo comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>

app/views/comentarios/show.html.erb
<html>
<head>
<title>Comentários</title>
	<meta content="charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
	<div id="page">
		<div id="headercom">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li class="active"><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">

						<p id="notice"><%= notice %></p>

<p>
  <b>Conteudo:</b>
  <%= @comentario.conteudo %>
</p>

<p>
  <b>Text:</b>
  <%= @comentario.conteudo %>
</p>

<p>
  <b>Comentavel:</b>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <b>Comentavel type:</b>
  <%= @comentario.comentavel_type %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>