config/routes.rb
VotaPrato::Application.routes.draw do
  devise_for :users

  resources :comentarios
  resources :restaurantes

  resources :qualificacaos
  resources :clientes
  root :to => "restaurantes#index" 

  match ':controller(/:action(/:id))(.:format)'
end

app/models/qualificacao.rb
#encoding:utf-8
class Qualificacao < ActiveRecord::Base
  attr_accessible :cliente_id, :nota, :restaurante_id, :valor_gasto

  validates_presence_of :nota, :message => "deve ser preenchido"
  validates_presence_of :valor_gasto, :message => "deve ser preenchido"

  validates_numericality_of :nota, :greater_than => 0, :less_than_or_equal_to => 10, :message => "nota entre 0 e 10"

  validates_numericality_of :valor_gasto, :greater_than => 0, :message => "deve ser maior que 0"

  validates_presence_of :cliente_id, :restaurante_id 
  validates_associated :cliente, :restaurante
  
  belongs_to :cliente
  belongs_to :restaurante

  has_many :comentarios, as: :comentavel

end
	

app/controllers/qualificacaos_controller.rb
class QualificacaosController < ApplicationController
  before_filter :authenticate_user!
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacaos = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @qualificacaos }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new
    @qualificacao = Qualificacao.new

    if params[:cliente]
@qualificacao.cliente = Cliente.find(params[:cliente])
end
if params[:restaurantes]
@qualificacao.restaurante = Restaurante.find(params[:restaurantes])
end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao =  Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacaos_url }
      format.json {head :no_content }
    end
  end
  end

app/helpers/qualificacaos_helper.rb
module QualificacaosHelper
end

app/views/qualificacaos/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @qualificacao.cliente %>
    <%= f.hidden_field 'cliente_id' %>
    <% else %>
    <p><%= f.label :cliente_id %><br />
      <%= f.collection_select(:cliente_id, Cliente.order('nome'), :id, :nome, {:prompt => true}) %></p>
      <% end %>

  </div>
    <div class="field">
    <% if @qualificacao.restaurante %>
<%= f.hidden_field 'restaurante_id' %>
<% else %>
<p><%= f.label :restaurante_id %><br />
<%= f.collection_select(:restaurante_id, Restaurante.order('nome'),:id, :nome, {:prompt => true}) %></p>
<% end %>

  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacaos/edit.html.erb
<html>
<head>
<title>Qualificações</title>
	<meta content="charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
	<div id="page">
		<div id="headerqua">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li class="active"><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<div>
							<h1>Editando Qualificação</h1>
							<%= render 'form' %>

							<%= link_to 'Show', @qualificacao %> |
							<%= link_to 'Back', qualificacaos_path %>
						</div>
						<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>

app/views/qualificacaos/index.html.erb
<html>
<head>
<title>Qualificações</title>
  <meta content="charset=utf-8">
  <link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
  <div id="page">
    <div id="headerqua">
      <div class="background">
        <h1><a href="#">Vota Prato</a></h1>
        <ul>
          <li><a href="http://localhost:3000/Clientes">Clientes</a></li>
          <li><a href="http://localhost:3000/Comentarios">Comentários</a></li>
          <li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
          <li class="active"><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
        </ul>
      </div>
    </div>
    <div id="giz">
      <div id="quadroesquerda">
        <div class="block">
          <div class="block-top"></div>
          <div class="block-content">

            <h1 align="center">~Lista de Qualificações~</h1>

<table align="center">
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacaos.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= qualificacao.valor_gasto %></td>
    <td><%= link_to 'Mostrar', qualificacao %></td>
    <td><%= link_to 'Editar', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Deletar', qualificacao, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />
<center>
<%= link_to 'Nova Qualificacao', new_qualificacao_path %>
</center>

</div>
          <div class="block-bottom"></div>
        </div>
      </div>
      <div id="quadrodireita">
        <div class="block">
          <div class="block-top"></div>
          <div class="block-content">
            Trabalho Realizado por Rodrigo e Vinicius.
            <br>
            <br>
            Ruby Three Cotia.
          </div>
          <div class="block-bottom"></div>
        </div>

  
      </div>
    </div>
</body>
</html>

app/views/qualificacaos/new.html.erb
<html>
<head>
<title>Comentários</title>
	<meta content="charset=utf-8">
</head>
<body>
	<div id="page">
		<div id="headercom">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li class="active"><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>
				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<div>
						<h1>Novo Qualificação</h1>
						<%= render 'form' %>
						<%= link_to 'Back', qualificacaos_path %>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>

app/views/qualificacaos/show.html.erb
<html>
<head>
<title>Qualificações</title>
	<meta content="charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/css.css">
</head>
<body>
	<div id="page">
		<div id="headerqua">
			<div class="background">
				<h1><a href="#">Vota Prato</a></h1>
				<ul>
					<li><a href="http://localhost:3000/Clientes">Clientes</a></li>
					<li><a href="http://localhost:3000/Comentarios">Comentários</a></li>
					<li><a href="http://localhost:3000/Restaurantes">Restaurantes</a></li>
					<li class="active"><a href="http://localhost:3000/Qualificacaos">Qualificações</a></li>

				</ul>
			</div>
		</div>
		<div id="giz">
			<div id="quadroesquerda">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">

						<p id="notice"><%= notice %></p>



<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= @qualificacao.valor_gasto %>
</p>


<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacaos_path %>

<% unless @qualificacao.comentarios.empty?%>
<%= comentarios @qualificacao %>
<% end %>
<%= novo_comentario(@qualificacao) %>

</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="quadrodireita">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						Trabalho Realizado por Rodrigo e Vinicius.
						<br>
						<br>
						Ruby Three Cotia.
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
</body>
</html>